import React from "react";

const Head = () => {
  return (
    <>
      <meta name="description" content="Generated by create next app" />
      <title>Next.js | Blog</title>
      <link rel="icon" href="/next.svg"></link>
    </>
  );
};

export default Head;
